FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword} \
    MYSQL_DATABASE=${MYSQL_DATABASE:-photopostapp} \
    MYSQL_USER=${MYSQL_USER:-photopostuser} \
    MYSQL_PASSWORD=${MYSQL_PASSWORD:-photopostpassword}

EXPOSE 3306
